server:
  port: 8801
spring:
  application:
    name: stream-rabbitmq-provider
  cloud:
    stream:
      binders: #配置要绑定的rabbitmq的服务信息
        #表示定义的名称，用于与binding整合
        defaultRabbit:
          #消息组件类型
          type: rabbit
      bindings:
        #通道名称
        output:
          #表示要使用的Exchange名称定义
          destination: studyExchange
          #设置消息类型，本次为json,文本则设置"test/plain"
          context-type: application/json
          binder: defaultRabbit
  rabbitmq:
    host: 1.15.58.197
    username: kevintam
    password: 123456
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔(默认为30秒)
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔
    instance-id: send-8801.com #在消息列表时显示主机名称
    prefer-ip-address: true #访问的路径变为ip地址