server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: serookie.com:8848 #配置nacos地址
management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露端口